name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'src/DocumentStorage'

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore src/DocumentStorage/DocumentStorage.sln

      - name: Build
        run: dotnet build src/DocumentStorage/DocumentStorage.sln --no-restore

      - name: Test
        run: dotnet test src/DocumentStorage/DocumentStorage.Test/DocumentStorage.Test.csproj --no-build --verbosity normal
